export const CTA_COPY_OPTIONS = [
  "learn more",
  "download",
  "apply now",
  "show now",
  "watch more",
  "subscribe",
  "sign up",
  "book now",
  "call now",
  "Contact Us",
  "listen now",
  "get showtimes",
  "order now",
  "get directions",
  "see menu",
  "get quote",
  "send message",
  "request time",
];
